function createfigure(exp_x1, R2_V1, RMSE_V1, MAE_V1, T_exec1)
%CREATEFIGURE(exp_x1, R2_V1, RMSE_V1, MAE_V1, T_exec1)
%  EXP_X1:  bar xvector
%  R2_V1:  bar yvector
%  RMSE_V1:  bar yvector
%  MAE_V1:  bar yvector
%  T_EXEC1:  bar yvector

%  由 MATLAB 于 13-Apr-2026 13:17:30 自动生成

% 创建 figure
figure1 = figure('WindowState','maximized',...
    'Name','SCI_Performance_Analysis',...
    'Color',[1 1 1]);

% 创建 subplot
subplot1 = subplot(4,1,1,'Parent',figure1);
hold(subplot1,'on');

% 创建 bar
bar(exp_x1,R2_V1,'Parent',subplot1,'FaceColor',[0.2 0.4 0.6],'BarWidth',0.5);

% 创建 plot
plot(exp_x1,R2_V1,'Parent',subplot1,'MarkerFaceColor',[1 1 1],'Marker','o',...
    'LineWidth',1.5,...
    'Color',[0.8 0.2 0.2],...
    'ZDataSource','');

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9148',...
    'Position',[1 0.914817915044943 0]);

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9307',...
    'Position',[2 0.930724899831722 0]);

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9537',...
    'Position',[3 0.953700288176103 0]);

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9661',...
    'Position',[4 0.966138223233909 0]);

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9714',...
    'Position',[5 0.97143365504 0]);

% 创建 text
text('Parent',subplot1,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','0.9760',...
    'Position',[6 0.97598620302196 0]);

% 创建 ylabel
ylabel('R^2 Score');

% 创建 title
title('(a) Global Accuracy Comparison','Units','normalized',...
    'VerticalAlignment','top');

% 取消以下行的注释以保留坐标区的 Y 范围
% ylim(subplot1,[0.864817915044943 1.05]);
box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% 设置其余坐标区属性
set(subplot1,'XTick',[1 2 3 4 5 6],'XTickLabel',...
    {'Exp.1','Exp.2','Exp.3','Exp.4','Exp.5','Exp.6'});
% 创建 colorbar
colorbar(subplot1);

% 创建 legend
legend(subplot1,'show');

% 创建 subplot
subplot2 = subplot(4,1,2,'Parent',figure1);
hold(subplot2,'on');

% 创建 bar
bar(exp_x1,RMSE_V1,'Parent',subplot2,'FaceColor',[0.2 0.6 0.4],...
    'BarWidth',0.5);

% 创建 plot
plot(exp_x1,RMSE_V1,'Parent',subplot2,'MarkerFaceColor',[1 1 1],...
    'Marker','square',...
    'LineWidth',1.2,...
    'Color',[0.1 0.3 0.1],...
    'ZDataSource','');

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','4.79',...
    'Position',[1 4.79251212974917 0]);

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','4.12',...
    'Position',[2 4.12401427608139 0]);

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','4.02',...
    'Position',[3 4.02277402723488 0]);

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','3.54',...
    'Position',[4 3.53989147819281 0]);

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','3.15',...
    'Position',[5 3.15096042373848 0]);

% 创建 text
text('Parent',subplot2,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.95',...
    'Position',[6 2.95356296281564 0]);

% 创建 ylabel
ylabel('RMSE (MPa)');

% 创建 title
title('(b) Global RMSE Comparison','Units','normalized',...
    'VerticalAlignment','top');

box(subplot2,'on');
grid(subplot2,'on');
hold(subplot2,'off');
% 设置其余坐标区属性
set(subplot2,'XTick',[1 2 3 4 5 6],'XTickLabel',...
    {'Exp.1','Exp.2','Exp.3','Exp.4','Exp.5','Exp.6'});
% 创建 legend
legend(subplot2,'show');

% 创建 colorbar
colorbar(subplot2);

% 创建 subplot
subplot3 = subplot(4,1,3,'Parent',figure1);
hold(subplot3,'on');

% 创建 bar
bar(exp_x1,MAE_V1,'Parent',subplot3,'FaceColor',[0.7 0.5 0.2],...
    'BarWidth',0.5);

% 创建 plot
plot(exp_x1,MAE_V1,'Parent',subplot3,'MarkerFaceColor',[1 1 1],...
    'Marker','diamond',...
    'LineWidth',1.2,...
    'Color',[0.4 0.2 0.1],...
    'ZDataSource','');

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','3.37',...
    'Position',[1 3.37256134211099 0]);

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.94',...
    'Position',[2 2.9357396242065 0]);

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.88',...
    'Position',[3 2.8835056930448 0]);

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.66',...
    'Position',[4 2.65692534031396 0]);

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.31',...
    'Position',[5 2.30587037375241 0]);

% 创建 text
text('Parent',subplot3,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'String','2.14',...
    'Position',[6 2.14466943825948 0]);

% 创建 ylabel
ylabel('MAE (MPa)');

% 创建 title
title('(c) Global MAE Comparison','Units','normalized',...
    'VerticalAlignment','top');

box(subplot3,'on');
grid(subplot3,'on');
hold(subplot3,'off');
% 设置其余坐标区属性
set(subplot3,'XTick',[1 2 3 4 5 6],'XTickLabel',...
    {'Exp.1','Exp.2','Exp.3','Exp.4','Exp.5','Exp.6'});
% 创建 colorbar
colorbar(subplot3);

% 创建 legend
legend(subplot3,'show');

% 创建 subplot
subplot4 = subplot(4,1,4,'Parent',figure1);
hold(subplot4,'on');

% 创建 bar
bar(exp_x1,T_exec1,'Parent',subplot4,'FaceColor',[0.5 0.5 0.5],...
    'BarWidth',0.5);

% 创建 plot
plot(exp_x1,T_exec1,'Parent',subplot4,'MarkerFaceColor',[1 1 1],...
    'Marker','^',...
    'LineWidth',1.5,...
    'ZDataSource','',...
    'Color',[0 0 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','  5.23',...
    'Position',[1 5.2335268 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','267.41',...
    'Position',[2 267.4142536 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','  3.18',...
    'Position',[3 3.1797076 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','  2.99',...
    'Position',[4 2.9860106 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','293.57',...
    'Position',[5 293.5673285 0]);

% 创建 text
text('Parent',subplot4,'VerticalAlignment','bottom',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'String','296.53',...
    'Position',[6 296.5269199 0]);

% 创建 ylabel
ylabel('Time (s)');

% 创建 title
title('(d) Runtime Comparison','Units','normalized',...
    'VerticalAlignment','top');

box(subplot4,'on');
grid(subplot4,'on');
hold(subplot4,'off');
% 设置其余坐标区属性
set(subplot4,'XTick',[1 2 3 4 5 6],'XTickLabel',...
    {'Exp.1','Exp.2','Exp.3','Exp.4','Exp.5','Exp.6'});
% 创建 colorbar
colorbar(subplot4);

% 创建 legend
legend(subplot4,'show');

